apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-worker
  namespace: fase4
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: payments-worker
  template:
    metadata:
      labels:
        app: payments-worker
    spec:
      containers:
        - name: payments-worker
          image: adinteltidev/fase4-payments-api:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: payments-config
          env:
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-user
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-pass
            - name: RabbitMq__VirtualHost
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-vhost
