<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Ms.Payments.Worker-e8c39196-c3d6-4d8b-9934-b794d52453d2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ms.Payments.Application\Ms.Payments.Application.csproj" />
    <ProjectReference Include="..\Ms.Payments.Infrastructure\Ms.Payments.Infrastructure.csproj" />
  </ItemGroup>
</Project>
